import type { Metadata } from "next";
import { SITE_NAME } from "./site";

/**
 * The site-wide share image, generated by src/app/opengraph-image.tsx and
 * served at /opengraph-image. Referenced explicitly because a page-level
 * `openGraph` object shallow-replaces the layout's (dropping the file-injected
 * image), so each page must re-declare it. Resolved against metadataBase.
 */
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "CLiKiT — We build brands that convert",
};

type PageMetaOptions = {
  title: string;
  description: string;
  /** Root-relative path, e.g. "/about". Resolved against metadataBase. */
  path: string;
  type?: "website" | "article";
};

/**
 * Build per-page metadata with a canonical URL and Open Graph / Twitter cards.
 * URLs are relative — Next resolves them against `metadataBase` (set in the
 * root layout), so canonical and og:url come out absolute.
 */
export function pageMeta({
  title,
  description,
  path,
  type = "website",
}: PageMetaOptions): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      siteName: SITE_NAME,
      type,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

/**
 * Serialize data for an inline <script>. JSON.stringify does NOT escape `<`,
 * `>` or `&`, so a value containing `</script>` would otherwise close the tag
 * and allow HTML/JS injection. Escaping those keeps the JSON valid while making
 * a `</script>` breakout impossible.
 */
export function serializeJsonLd(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026");
}
